### ISSUE TITLE
"ValueError: year is out of range" Error Messages

### ISSUE THREAD

**Issue by cshanahan** [PoorBillionaire/Windows-Prefetch-Carver#4]
Hello,

I am consistently getting error messages related to byte (time) values that are not being handled correctly. These errors cause the script to fail, as opposed to skipping the input block and continuing.

>Traceback (most recent call last):
  File "prefetch-carve.py", line 212, in <module>
    main()
  File "prefetch-carve.py", line 204, in main
    prefetchCarve(m, o, output_type="csv")
  File "prefetch-carve.py", line 141, in prefetchCarve
    file_info, offset = parse_file_information(header[u'version'], mfile, offset)
  File "prefetch-carve.py", line 95, in parse_file_information
    return process_fileinfo_members(file_info_dict), offset
  File "prefetch-carve.py", line 104, in process_fileinfo_members
    filetime_to_human(fileinfo_dict[u'last_run_time'])
  File "prefetch-carve.py", line 115, in filetime_to_human
    return str(datetime.utcfromtimestamp(float(filetime) * 1e-7 - 11644473600))
ValueError: year is out of range

I am running the latest version (end of May) against EWF files that are mounted using ewfmount. Each of the EWF files contain a single NTFS volume from Windows 7 Pro systems.

If you need more information, please feel free to contact me.

Thanks.

/Chris

**Comment by PoorBillionaire** [comment]
Thanks Chris, I apologize that you encountered this breaking condition while using my script - I should have identified this. I'm typing this as I walk into a meeting, but I'll have a fix for you this afternoon.

Thanks again,

--
Adam

**Comment by PoorBillionaire** [comment]
Chris, sorry for the delay. Unfortunately I didn't encounter this issue wile running the script across several of my own test images. 

Commit e842626be893e5dfad38a9fe1d8b8462b63799cc takes care of this as a temporary solution. I'm in the process of adding logging facilities and more granular error-handling.

I'll keep this issue open until I hear back. Thanks again.

--
Adam

**Comment by PoorBillionaire** [comment]
Closing this one out. Chris, thanks for notifying me of this bug.

--
Adam
